In [6]:
# quizz caculations
import numpy as np

A = np.array([[2,3],[5,6]])
np.linalg.det(A)

np.float64(-2.9999999999999982)

In [9]:
np.linalg.det(A**2)

np.float64(-80.99999999999996)

In [13]:
M = np.array([[1,0,1],[0,1,0],[1,1,1]])
N = np.array([[2,8,7],[4,3,9],[1,9,5]])
np.linalg.det(M@N)

np.float64(0.0)

In [14]:
M@N

array([[ 3, 17, 12],
       [ 4,  3,  9],
       [ 7, 20, 21]])

In [28]:
m = [[3,2],[5,8]]
np.cov(m, rowvar=False)

array([[ 2.,  6.],
       [ 6., 18.]])

In [19]:
P9 = np.array([[70,2,2],[110,4,2]])
mu = P9.mean(axis=0)

In [21]:
P9-mu

array([[-20.,  -1.,   0.],
       [ 20.,   1.,   0.]])

In [26]:
d = np.cov(P9, rowvar=False)
d

array([[800.,  40.,   0.],
       [ 40.,   2.,   0.],
       [  0.,   0.,   0.]])

In [27]:
np.linalg.eig(d)

EigResult(eigenvalues=array([802.,   0.,   0.]), eigenvectors=array([[ 0.99875234, -0.04993762,  0.        ],
       [ 0.04993762,  0.99875234,  0.        ],
       [ 0.        ,  0.        ,  1.        ]]))